### ISSUE TITLE
Update examples for reading frame paragraphs in word documents

### ISSUE THREAD

**Issue by openize-words-gists** [openize-words-gists/Openize.Words-for-.NET#3]
[v24.6.0](https://github.com/openize-words/Openize.Words-for-.NET/releases/tag/v24.6.0) comes with support for paragraphs frames so a gist and usage examples should cover loading/reading frame paragraphs in word documents.

**Comment by sabir-aspose** [comment]
Gist Added: https://gist.github.com/openize-words-gists/a577267cc39bae46ace887d0860422db
