### ISSUE TITLE
Update examples for modifying frame paragraphs in word documents

### ISSUE THREAD

**Issue by openize-words-gists** [openize-words-gists/Openize.Words-for-.NET#4]
[v24.6.0](https://github.com/openize-words/Openize.Words-for-.NET/releases/tag/v24.6.0) comes with support for paragraphs frames so a gist and usage examples should cover modifying frame paragraphs in word documents.

**Comment by sabir-aspose** [comment]
Gist added: https://gist.github.com/openize-words-gists/08e214d1abbf7603657d9b42e3ed9822
